[package]
name = "branches"
version = "0.1.0"
authors = ["Mark Sherry <marks@sortable.com>"]

[dependencies]
git2 = "0.7"
failure = "0.1"
colored = "1.6"
chrono-humanize = "0.0.11"
chrono = "0.4"
structopt = "0.2"
